### ISSUE TITLE
Implement UUID for users

### ISSUE THREAD

**Issue by mattthw** [mmccoy37/GTMovies#18]
- create a UUID for each user.
- update existing methods (should only have to change User's equals(User u) method )
- ACCOUNTS will use a HashMap of uuid:User rather than a HashSet of <User>

This is needed ASAP. In future milestones we will be be storing the user's name in more than just the User object. If we compare only based on username then we will have to update all the other placed this username is stored when a user changes it (in profile editor).

**Comment by jinu-jang** [comment]
Is this still an issue?
Was this not solved via GTiD
