### ISSUE TITLE
Static variable in JSON parser

### ISSUE THREAD

**Issue by jinu-jang** [mmccoy37/GTMovies#19]
Target: "TomatoParser.java"

The norm seems to be making the variables in the JSON parser static.
No idea why and in how I'm imagining the scheme of things this seems to be harmful.

The TomatoParser as it has the ability to go into an URL and get the JSON from it, can be used in many cases.
However, making the variable static would make that impossible.

Then again, I have the feeling that maybe it's static because of it having to be used in an AsyncTask and maybe that has something to do with this???

Right now I have just set it to non-static

**Comment by jinu-jang** [comment]
Upon a realization made it back to static.
TomatoParser does not need to be accessed by any other class.

Still don't know why static is better though

**Comment by mattthw** [comment]
Is this a question

**Comment by mattthw** [comment]
@jimjang95

**Comment by jinu-jang** [comment]
yup

**Comment by jinu-jang** [comment]
Well this doesnt matter anymore
