### ISSUE TITLE
Unnecessary AppPreferences

### ISSUE THREAD

**Issue by jinu-jang** [mmccoy37/GTMovies#32]
In AppPreferences, there exists an option to change Display Name.
I made it so that it actually changes the display name, but I say we just get rid of it.
Completely unnecessary to be able to change the display name in two places:
1. The Edit Profile
2. Said AppPreference

**Comment by jinu-jang** [comment]
Just realized this is an open issue by Matt (Issue #11 ).
Closing thread.

**Comment by mattthw** [comment]
you cannot change the display name now
